export default [
  {
    name: 'Олександр Москалець',
    photo: '../../images',
    position: 'Team lead',
    github: 'https://github.com/MoskaletsOleksandr',
    linkedin: 'https://www.linkedin.com/in/oleksandr-moskalets-41a54b23b/?original_referer=',
  },
  {
    name: 'Олена Бєляєва',
    photo: '../../images',
    position: 'Scrum master',
    github: 'https://github.com/helenbyelyayeva',
    linkedin: 'https://www.linkedin.com/in/helen-byelyayeva-326779234',
  },
  {
    name: 'Денис Денисюк',
    photo: '../../images',
    position: 'Front-end Developer',
    github: 'https://github.com',
    linkedin: 'https://www.linkedin.com',
  },
  {
    name: 'Ірина Петренко',
    photo: '../../images',
    position: 'Front-end Developer',
    github: 'https://github.com/IrynaPetr',
    linkedin: 'https://www.linkedin.com/in/%D1%96%D1%80%D0%B8%D0%BD%D0%B0-%D0%BF%D0%B5%D1%82%D1%80%D0%B5%D0%BD%D0%BA%D0%BE-a87b17265/',
  },
  {
    name: 'Ірина Калашнікова',
    photo: '../../images',
    position: 'Front-end Developer',
    github: 'https://github.com/iKalashnikova',
    linkedin: 'https://www.linkedin.com',
  },
  {
    name: 'Олександр Казьмерчук',
    photo: '../../images',
    position: 'Front-end Developer',
    github: 'https://github.com/Oleksandr-Kharkiv',
    linkedin: 'https://www.linkedin.com',
  },
  {
    name: 'Аліна Присяжнюк',
    photo: '',
    position: 'Front-end Developer',
    github: 'https://github.com/AlinaPrysiazhniuk',
    linkedin: 'https://www.linkedin.com',
  },
  {
    name: 'Ігор Пінчук',
    photo: '../../images',
    position: 'Front-end Developer',
    github: 'https://github.com/IhorPinchuk',
    linkedin: 'https://www.linkedin.com',
  },
  {
    name: 'Мар\'яна Собашевська',
    photo: '../../images',
    position: 'Front-end Developer',
    github: 'https://github.com',
    linkedin: 'https://www.linkedin.com',
  },
  {
    name: 'Матвій Прищенко',
    photo: '../../images',
    position: 'Front-end Developer',
    github: 'https://github.com',
    linkedin: 'https://www.linkedin.com',
  },
  {
    name: 'Олександр Миронець',
    photo: '../../images',
    position: 'Front-end Developer',
    github: 'https://github.com/AleksMyronets',
    linkedin: 'https://www.linkedin.com',
  },
  {
    name: 'Сергій Трефель',
    photo: '../../images',
    position: 'Front-end Developer',
    github: 'https://github.com',
    linkedin: 'https://www.linkedin.com',
  }
]