const refs = {
    searchFormEl: document.querySelector('.form-search'),
    searchInputEl: document.querySelector('.input-search'),
    galleryContainerEl: document.querySelector('.gallery-container'),
    galleryListEl: document.querySelector('.gallery-list'),
    aboutTeamBtn: document.querySelector('.about-team'),
    btnUpEl: document.querySelector('.btn-up'),
    bodyEl: document.querySelector('body'),
    backdropMovieModal: document.querySelector('.backdrop'),
    movieModalEl: document.querySelector('div[data-movie-modal]'),
    movieModalFilmInfoEl: document.querySelector('.js-film-info'),
    modalCloseBtn: document.querySelector('button[data-movie-modal-close]'),
    // addToWatchedBtn: document.querySelector('button[data-btn-to-watched]'),
    //   addToQueueBtn: document.querySelector('button[data-btn-to-queue]'),
    teamModalOpenBtn: document.querySelector('button[data-team-modal-open]'),
    teamModalCloseBtn: document.querySelector('button[data-team-modal-close]'),
    teamModal: document.querySelector('div[data-team-modal]'),
    pagination: document.querySelector('#pagination'),
};
export default refs;
