const refs = {
  searchFormEl: document.querySelector('.form-search'),
  searchInputEl: document.querySelector('.input-search'),
  galleryContainerEl: document.querySelector('.gallery-container'),
  galleryListEl: document.querySelector('.gallery-list'),
  galleryLibListEl: document.querySelector('.gallery-lib-list'),
  aboutTeamBtn: document.querySelector('.about-team'),
  btnUpEl: document.querySelector('.btn-up'),
  bodyEl: document.querySelector('body'),
  backdropMovieModal: document.querySelector('.backdrop'),
  movieModalEl: document.querySelector('div[data-movie-modal]'),
  movieModalFilmInfoEl: document.querySelector('.js-film-info'),
  modalCloseBtn: document.querySelector('button[data-movie-modal-close]'),
  // addToWatchedBtn: document.querySelector('button[data-btn-to-watched]'),
  //   addToQueueBtn: document.querySelector('button[data-btn-to-queue]'),
  teamModalOpenBtn: document.querySelector('button[data-team-modal-open]'),
  teamModalCloseBtn: document.querySelector('button[data-team-modal-close]'),
  teamModal: document.querySelector('div[data-team-modal]'),
  pagination: document.querySelector('#pagination'),
  headerEl: document.querySelector('.header'),
  btnThemeEl: document.querySelector('.btn-theme'),
  btnIconMoonEl: document.querySelector('.btn-icon-moon'),
  btnIconSunEl: document.querySelector('.btn-icon-sun'),

  headerContainerEl: document.querySelector('.header-filmoteka'),
  logoHeader: document.querySelector('.header-logo'),
  logoTextHeader: document.querySelector('.header-text-logo'),
  iconFilmHeader: document.querySelector('.icon-film'),
  //headerEl: document.querySelector('.header'),
  libraryBtn: document.querySelector('.library-buttons'),
  watchedButton: document.querySelector('.watched-btn'),
  queueButton: document.querySelector('.queue-btn'),
  searchLib: document.querySelector('.search--lib'),
  galleryFixed: document.querySelector('.gallery-no-fixed'),

};
export default refs;
